[tool:pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --asyncio-mode=auto
pythonpath = .
norecursedirs = .aws-sam
markers =
    asyncio: mark a test as asyncio